version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Zurich
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /share/Container/mount_volumes/plex/library:/config
      - /share/TVSeries:/tv
      - /share/Movies:/movies
      - /share/Container/mount_volumes/nextcloud/nc_data/data/Daniel/files/Photos/:/pictures
      - /share/Multimedia/Musik/:/Music
    ports:
      - 32400:32400
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
