name: nextcloud 

services:
  nc:
    build: . 
    container_name: nextcloud-server
    restart: unless-stopped
    ports:
      - 5555:443
    depends_on:
      - mariadb
      - redis
    volumes:
      - ${NC_VOLUME}:/var/www/html
    networks:
      - ncnet
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - NEXTCLOUD_INIT_HTACCESS=true
      - TZ=Europe/Zurich
#    healthcheck:
#      test: ["CMD", "/usr/bin/healthcheck"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - ${RD_VOLUME}:/data
    networks:
      - ncnet
    expose:
      - 6379
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mariadb:
    image: mariadb:latest
    container_name: nextcloud-mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    networks:
      - ncnet
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    networks:
      - ncnet
    volumes:
      - ${NC_VOLUME}:/var/www/html
    entrypoint: /cron.sh
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis

volumes:
  db_data:
    driver: local
  nc_data:
    driver: local
  redis:
    driver: local

networks:
  ncnet:

