version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user:  
    network_mode: 'host'
    volumes:
      - /share/Container/mount_volumes/jellyfin/config:/config
      - /share/Container/mount_volumes/jellyfin/cache:/cache
      - type: bind
        source: /share/Container/mount_volumes/nextcloud/nc_data/data/Daniel/files/Photos
        target: /media/Album
        read_only: true
      - type: bind
        source: /share/Multimedia/Musik/
        target: /media/Musik
        read_only: true
      - type: bind
        source: /share/Multimedia/Books/
        target: /media/Books
        read_only: true
      - type: bind
        source: /share/Movies/
        target: /media/Movies
        read_only: true
      - type: bind
        source: /share/TVSeries/
        target: /media/TVSeries
        read_only: true
      - type: bind
        source: /share/Multimedia/Fotobücher
        target: /media/Photobooks
        read_only: true
    restart: 'unless-stopped'
    ports:
      - 8096:8096
      - 8920:8920
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - TZ=Europe/Zurich
    # Optional - alternative address used for autodiscovery
    #  - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
    #  - 'host.docker.internal:host-gateway'

