version: '2'
networks:
  sparknetwork:
services:
  spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    restart: always    

  spark-worker-1:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    restart: always

  spark-worker-2:
      image: bde2020/spark-worker:2.3.0-hadoop2.7
      container_name: spark-worker-2
      depends_on:
        - spark-master
      ports:
        - "8083:8081"
      environment:
        - "SPARK_MASTER=spark://spark-master:7077"
      restart: always

  jupyter:
    image: insilentio/anaconda
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ..:/opt/notebooks
    restart: always
    command: /bin/bash -c 'jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root'
    links:
      - cassandra:cassandra1

  cassandra:
    image: cassandra
    container_name: cassandra1
    ports:
      - "9042:9042"
    volumes:
      - ../cassandra:/var/lib/cassandra/data
    restart: always
